- name: install nginx
  package:
    name: nginx
    state: present
  notify: nginx enable

# By default, se linux blocks nginx from:
#   * listening on port 53
#   * proxying to another server
#
# `selinux_permissive` requires python packages provided by `policycoreutils-python-utils`
- name: install se linux management packages
  package:
    name: policycoreutils-python-utils
    state: present
- name: set se linux to permissive mode for nginx
  selinux_permissive:
    name: httpd_t
    permissive: true

- name: configure firewall
  firewalld:
    service: dns
    immediate: yes
    permanent: yes
    state: enabled

- name: nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: nginx update
