- name: install nginx
  package:
    name: nginx
    state: present
  notify: nginx enable

// TODO se linux blocks nginx from binding to DNS ports (and possibly proxying?)

- name: configure firewall
  firewalld:
    service: dns
    immediate: yes
    permanent: yes
    state: enabled

- name: nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: nginx update
